services:
  - name: registration-form
    type: web
    env: docker
    repo: https://github.com/guadalahacks/registration_form
    branch: main 
    plan: free
    envVars:
      - key: PORT
        value: 80
