services:
  backend:
    type: web
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      DATABASE_URL: ${DATABASE_URL}
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    build:
      dockerfilePath: ./backend/Dockerfile
    serviceDetails:
      ports:
        - port: 3000
  frontend:
    type: web
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    plan: free
    healthCheckPath: /
    autoDeploy: true
    build:
      dockerfilePath: ./frontend/Dockerfile
    serviceDetails:
      ports:
        - port: 5173
databases:
  - name: registros
    plan: free
    databaseType: postgresql
    envVars:
      DATABASE_URL: ${DATABASE_URL}